### ISSUE TITLE
Different methods to get underlying ps in WrappedPreparedStatement

### ISSUE THREAD

**Issue by ecki** [ironjacamar/ironjacamar#280]
In `org.jboss.jca.adapters.jdbc.WrappedPreparedStatement` the different delegated methods all use `lock`/`unlock` and `checkState` but some of them use the `ps` field directly, others use `getUnderlyingPreraedStatement` (which does lock+check itself). Is this intentional or should all use `ps.` directly?

It looks like at the beginning of the flle ps. was used (setBoolean, setByte, ..., setArray, getParameterMetaDate), and since getPoolable/setPoolable used the underyling one the following methds used it by accident:

https://github.com/ironjacamar/ironjacamar/blob/1.2/adapters/src/main/java/org/jboss/jca/adapters/jdbc/WrappedPreparedStatement.java

If it is intentional, I would suspect it should be used in the old methods as well (and we can skip the checkState() call then.

**Comment by ecki** [comment]
sorry, wrong branch :)

**Comment by ecki** [comment]
replaced old linenumbers with a source link.

**Comment by jesperpedersen** [comment]
https://github.com/ironjacamar/ironjacamar/commit/b8e6d66203265cf7fc74745b1b443bfb0d7eab14 fixes this
