### ISSUE TITLE
Source of ironjacamar-deployers-fungal

### ISSUE THREAD

**Issue by tcollignon** [ironjacamar/ironjacamar#534]
Hello

I search the source code of ironjacamar-deployers-fungal jar, do you know where it is ?
(particularly org.jboss.jca.deployers.fungal.RADeployer)

Thanks in advance

**Comment by gaol** [comment]
The source codes you are searching are in `1.x` branch of IronJacamar, see: https://github.com/ironjacamar/ironjacamar/blob/1.2/deployers/src/main/java/org/jboss/jca/deployers/fungal/RADeployer.java

BTW, I think it would be better to ask thus questions in ironjacamar groups: [users group](https://groups.google.com/forum/#!forum/ironjacamar-users) and [developers groups](https://groups.google.com/forum/#!forum/ironjacamar-developers)

**Comment by tcollignon** [comment]
Thank you very much
Indeed groups will be a better way

I'm not seing RADeployer in master branch, you have change this ? What is the replacement?

I'm trying to use RADeployer with jar including resource.rar to easily manage this with Maven.

**Comment by gaol** [comment]
There are no releases based on master branch(2.x) yet. For the moment, I think it would be better to use the latest release, see: http://www.ironjacamar.org/download.html, and for the maven artifacts, here it is: http://repo1.maven.org/maven2/org/jboss/ironjacamar/ironjacamar-deployers-fungal/1.2.7.Final/

**Comment by maeste** [comment]
I'm closing this issue because this kind of discussion should go through our forumus and not issue tracker.
Thanks for your interest and please join us on our forum:
user forum: https://groups.google.com/forum/#!forum/ironjacamar-users
developer forum: https://groups.google.com/forum/#!forum/ironjacamar-developers
