### ISSUE TITLE
Log issue: Closing a result set you left open, please do your own housekeeping 

### ISSUE THREAD

**Issue by LukyBruce** [ironjacamar/ironjacamar#762]
Hi guys, 

I saw in my project, there are many annoying logs "Closing a result set you left open, please do your own housekeeping” that was possibly caused by below method. In function unregisterStatement, the field trackStatement was not decreased. 

```
  void unregisterStatement(WrappedStatement ws)
   {
      if (trackStatements == BaseWrapperManagedConnectionFactory.TRACK_STATEMENTS_FALSE_INT)
         return;
      synchronized (this)
      {
         if (statements != null)
            statements.remove(ws);
      }
   }
```
When the WrappedStatement is closing, it will also internally close the resultset, the following code will check if trackedStatement is zero, and log above warning when it's not zero.

```
   protected void closeResultSets()
   {
      if (lc.getTrackStatements() == BaseWrapperManagedConnectionFactory.TRACK_STATEMENTS_FALSE_INT)
         return;

      synchronized (this)
      {
         if (resultSets == null)
            return;

         for (Iterator<Map.Entry<WrappedResultSet, Throwable>> i = resultSets.entrySet().iterator(); i.hasNext();)
         {
            Map.Entry<WrappedResultSet, Throwable> entry = i.next();
            WrappedResultSet resultSet = entry.getKey();

            if (lc.getTrackStatements() == BaseWrapperManagedConnectionFactory.TRACK_STATEMENTS_TRUE_INT)
            {
               Throwable stackTrace = entry.getValue();
               lc.getLogger().closingResultSet(resultSet.toString(), stackTrace);
            }
```

Can you check and fix accordingly?

Regards,
LuckyBruce

**Comment by tadamski** [comment]
hi @LukyBruce

trackStatement field is a flag, not a counter and it shouldn't be decremented. You can set it to TRACK_STATEMENTS_NOWARN_INT to prevent those warnings from being printed, but I would suggest making sure that you are closing each ResultSet.
Regards,
Tomek

**Comment by LukyBruce** [comment]
Hi @tadamski, 

Thanks for the answer, yes, if I explicitly close the resultset first, this can get rid of the warnings. But as per the most the of implementations of JDBC driver as well as this lib, closing Preparestatement will also close the result set. 

We have plenty of legacy code which only close the preparestatement, but not the resultset, thus causing lots of warnings.

Best regards,
Bruce

**Comment by tadamski** [comment]
hi @LukyBruce 

In such case you can add following config to Wildfly datasource configuration:

`
                    <statement>
                        <track-statements>nowarn</track-statements>
                    </statement>
`
It would turn off those warnings.

Regards,
Tomek

**Comment by LukyBruce** [comment]
@tadamski ,

Thanks, I have one more question, if I turn off this warn, if prepare statement itself was not closed, are there still warnings?

Best regards,
Bruce

**Comment by tadamski** [comment]
hi @LukyBruce

If you turn off the warning the messages should not be printed.

Regards,
Tomek
