### ISSUE TITLE
ironjacamar-validator-maven 1.4.36.Final+ fails

### ISSUE THREAD

**Issue by fcorneli** [ironjacamar/ironjacamar#774]
I get the following error when trying to invoke this Maven plugin:
```
No plugin descriptor found at META-INF/maven/plugin.xml
```
And indeed, this file is no longer part of the `ironjacamar-validator-maven` JAR.

**Comment by tadamski** [comment]
hi @fcorneli 
Thanks for reporting this bug. I have fixed it and plugin should work correctly from version 3.0.1.Final.
