### ISSUE TITLE
Split core into reusable modules

### ISSUE THREAD

**Issue by gastaldi** [ironjacamar/ironjacamar#779]
I'm writing https://github.com/quarkiverse/quarkus-ironjacamar/, which is a Quarkus extension for IronJacamar. I'd like to reuse the `ConnectionManager` feature from IronJacamar, which is available in https://github.com/ironjacamar/ironjacamar/tree/main/core/impl/src/main/java/org/jboss/jca/core/connectionmanager but because it's in a single `core` module, some dependencies are not necessary (JBoss Threads is used in the `WorkManager` implementation for example). 

Would it be possible to split into submodules and then `core` would depend on them? Eg. `ironjacamar-core-connectionmanager-api`,  `ironjacamar-connectionmanager-impl` etc?

**Comment by tadamski** [comment]
hi @gastaldi
I will look at that. Would you be able to create a JIRA in IronJacamar [project](https://issues.redhat.com/browse/JBJCA) and describe how the split would look like (how many modules and what functionalities)?

**Comment by gastaldi** [comment]
@tadamski thanks for the feedback! I'm using the connection manager implementation, so that's the module I would consider more important at the moment. 

I'll see if I can put that into a JIRA

**Comment by gastaldi** [comment]
I created https://issues.redhat.com/browse/JBJCA-1478 asking for that, closing this issue
