### ISSUE TITLE
Upgrade JBoss Threads to 3.5.0.Final

### ISSUE THREAD

**Issue by gastaldi** [ironjacamar/ironjacamar#780]
It would be nice to upgrade to the latest JBoss Threads version (3.5.0.Final as of now). Some frameworks (like Quarkus) use the latest version and bumping it would help a lot in https://github.com/quarkiverse/quarkus-ironjacamar

**Comment by tadamski** [comment]
Hi @gastaldi 
I'm looking into that but this is not trivial because functionality of BlockingExecutor is required by JCA spec. I have created 
 [JBJCA-1476](https://issues.redhat.com/browse/JBJCA-1476)  [JBJCA-1477](https://issues.redhat.com/browse/JBJCA-1477) to trace the progress of this.

**Comment by gastaldi** [comment]
I see. In my case the Quarkus extension uses Vert.x, so I'm relying on its executors atm and not using JBoss threads (at least not directly)

**Comment by gastaldi** [comment]
Since they are already created in JIRA, let's close this one
