### ISSUE TITLE
CachedPreparedStatement must clear parameters of the wrapped statement on close

### ISSUE THREAD

**Issue by l-k-test** [ironjacamar/ironjacamar#783]
Method 
`public void close()`
performs "Reset the defaults" if it decides to cache the prepared statement. Unfortunately it does not clear parameters of the underlying prepared statement. Depending on the statement the parameters can be quite large. If the statement is not used very often and remains in the cache, all those parameters contribute to the memory footprint of the running process and can even lead to an OOM.

**Comment by tadamski** [comment]
hello@l-k-test,
 thanks for pointing this out - I have created https://issues.redhat.com/browse/JBJCA-1479 to follow this issue

**Comment by tadamski** [comment]
fixed - it will be present in ironjacamar 3.0.6.Final
